'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Play,Shield,HeartPulse,ArrowRight} from 'lucide-react';
import {hostedStep,weeklyLiving} from '../lib/hosting';
import {age,adultAge,money,date,events,perform} from '../lib/game';
import type {Game,Hosting} from '../lib/game';

type Props={game:Game,slotId:string,onCommit:(next:Game,expected:Game,slot:string,history:boolean,revision:number)=>boolean,getRevision:()=>number,onEnterBattle:()=>void};
const temperaments=[['adventure','冒险','接受风险，重视高额收益与突破机会'],['balanced','平和','优先熟练度与稳定收益，适度避险'],['cautious','谨慎','避开受伤与高花费，优先安全选项']] as const;
const rates=[1,2,4,8] as const;
// 模拟回放只保留重要时刻：突破上限、转职解锁、职业剧情（含分叉）；事件日志标题为「事件名 · 选项名」，按前缀匹配
const specialLog=(e:{title:string,text:string,changes?:string[]})=>{const t=e.title||'';const ev=events.filter(x=>t.startsWith(x.title)).sort((a,b)=>b.title.length-a.title.length)[0];if(ev)return ev.id.startsWith('mastery')||ev.id.startsWith('farmer')||ev.id.startsWith('knight')||ev.id.startsWith('story')||ev.choices.some(c=>c.flag);return t.includes('新的道路')||(e.changes||[]).some(c=>String(c).includes('解锁转职'))};

export default function HostingPanel({game,slotId,onCommit,getRevision,onEnterBattle}:Props){
 const existing=game.hosting;const [action,setAction]=useState<Hosting['action']>(existing?.action||'work'),[temperament,setTemperament]=useState<Hosting['temperament']>(existing?.temperament||'balanced'),[staminaOn,setStaminaOn]=useState(existing?.staminaBelow!==null&&existing?.staminaBelow!==undefined),[hpOn,setHpOn]=useState(existing?.hpBelow!==null&&existing?.hpBelow!==undefined),[stamina,setStamina]=useState(existing?.staminaBelow??35),[hp,setHp]=useState(Math.min(existing?.hpBelow??10,10)),[running,setRunning]=useState(false),[message,setMessage]=useState(existing?.reason||'尚未开始模拟。'),[rate,setRate]=useState(2),[modal,setModal]=useState(false),[replay,setReplay]=useState<{day:number,title:string,text:string,changes?:string[]}[]>([]);
 const prevActive=useRef(!!game.hosting?.active),prevBattle=useRef(game.battle);
 useEffect(()=>{const a2=!!game.hosting?.active;const settled=prevBattle.current!==null&&game.battle===null&&a2;if((a2&&!prevActive.current||settled)&&!running)run(game);prevActive.current=a2;prevBattle.current=game.battle},[game.hosting?.active,game.battle]);
 const serial=useRef(0),live=useRef(true),current=useRef(game),revision=useRef(getRevision()),rateRef=useRef(2),replayLen=useRef(0),replayBox=useRef<HTMLDivElement|null>(null);current.current=game;
 useEffect(()=>{live.current=true;return ()=>{live.current=false;serial.current++}},[]);
 useEffect(()=>{if(game.battle?.done&&game.battle.won&&game.hosting?.active&&!running){revision.current=getRevision();setModal(true)}if(game.battle?.done&&!game.battle.won&&game.hosting?.active){const next={...game,hosting:{...game.hosting!,active:false,reason:'战斗失利，模拟已暂停。请先处理伤势，再决定是否继续。'}};commit(next,game,false);setModal(false)}},[game.battle?.done,game.battle?.won,game.hosting?.active]);
 useEffect(()=>{if(running&&game!==current.current){setRunning(false);setModal(false);setMessage('人物状态已变化，模拟已停止。')}},[game,running]);
 useEffect(()=>{const el=replayBox.current;if(el)el.scrollTop=el.scrollHeight},[replay]);
 const pickRate=(r:number)=>{setRate(r);rateRef.current=r};
 const commit=(next:Game,base:Game,history:boolean)=>{if(!onCommit(next,base,slotId,history,revision.current)){setRunning(false);setModal(false);setMessage('存档已变化，请重新开始模拟。');return false}revision.current=getRevision();current.current=next;return true};
 const config=():Hosting=>({action,temperament,staminaBelow:staminaOn?Math.max(0,Math.min(100,Math.round(stamina))):null,hpBelow:hpOn?Math.max(1,Math.min(10,Math.round(hp))):null,resting:false,forcedWork:false,targetDays:36000,steps:2000,active:true,completed:existing?.completed||0,reason:'模拟已启动。'});
 async function run(base:Game){const ticket=++serial.current;setRunning(true);setModal(true);setReplay([]);replayLen.current=base.log.length;const maxDays=base.hosting?.targetDays||36000;const maxSteps=2000;const startDay=base.day;let local=base;for(let step=0;step<maxSteps;step++){if(!live.current||ticket!==serial.current)return;const result=hostedStep(local);if(!commit(result.state,local,!result.error)){setRunning(false);setModal(false);return}local=result.state;if(local.log.length>replayLen.current){const fresh=local.log.slice(replayLen.current).map(e=>({day:e.day,title:e.title,text:e.text,changes:e.changes})).filter(specialLog);replayLen.current=local.log.length;setReplay(prev=>[...prev,...fresh].slice(-400));}setMessage(result.reason);if(result.error){const forkPaused=!!local.hosting?.active;setRunning(false);if(!forkPaused)setModal(false);return}if(!local.hosting?.active){setRunning(false);setModal(false);return}if(local.day-startDay>=maxDays)break;await new Promise(resolve=>setTimeout(resolve,Math.round(80/rateRef.current)));}if(ticket===serial.current){const done=local.day-startDay;const label=done>=360?Math.floor(done/360)+'年'+((done%360)>=30?Math.floor((done%360)/30)+'个月':''):done>=30?Math.floor(done/30)+'个月':done+'天';const paused={...local,hosting:{...local.hosting!,active:false,reason:'本次已完成约'+label+'模拟，请查看经历后继续。'}};commit(paused,local,false);setRunning(false);setModal(false);setMessage(paused.hosting.reason)}}
 function recover(){if(game.dead||game.retired){setMessage('这段人生已经结束，无需恢复。');return}if(running)stop();const r=perform(game,'recover','');if(r.error){setMessage(r.error);return}if(!commit(r.state,game,false))return;setMessage('已暂停模拟，养精蓄锐两日，恢复至最佳状态。可再次点「开始模拟」继续。')}
 function start(){if(game.dead||game.retired)return;const need=weeklyLiving(game)*2;if(game.cash<need){setMessage('现金不足两周食宿（约'+money(need)+'，当前'+money(game.cash)+'），模拟不会开始。先攒够一两周食宿费再来。');return}revision.current=getRevision();const planned={...game,hosting:config()};if(commit(planned,game,false))void run(planned)}
 function stop(){serial.current++;const base=current.current;if(base.hosting){const paused={...base,hosting:{...base.hosting,active:false,reason:'你停止了模拟。'}};commit(paused,base,false)}setRunning(false);setModal(false);setMessage('你停止了模拟。')}
 const forkEvent=game.event?events.find(e=>e.id===game.event):undefined;
 const isFork=!!(forkEvent&&forkEvent.choices.some(c=>c.flag));
 function chooseFork(i:number){if(!forkEvent)return;const r=perform(game,'event',String(i));if(r.error){setMessage(r.error);return}if(!commit(r.state,game,true))return;setMessage('剧情选择已记录：「'+forkEvent.choices[i].label+'」，可继续模拟。')}
 const forkBlock=()=>forkEvent?<div className="fork-prompt"><div className="fork-head"><b>剧情分叉 · 请做出选择</b><small>选择将决定剧情走向</small></div><p className="fork-title">{forkEvent.title}</p><p className="fork-text">{forkEvent.text.slice(0,140)}{forkEvent.text.length>140?'……':''}</p><div className="event-choices">{forkEvent.choices.map((c,i)=><button key={i} onClick={()=>chooseFork(i)}><b>{String.fromCharCode(65+i)}</b><span>{c.label}<small>{c.detail}{c.days>0?' · 另计食宿':''}</small></span><ArrowRight size={16}/></button>)}</div></div>:null;
 const pb=game.pendingBattle;
 const battleBlock=()=>pb?<div className="fork-prompt battle-prompt"><div className="fork-head"><b>{pb.kind==='遭遇'?'战斗遭遇 · 请做出选择':'讨伐任务 · 请做出选择'}</b><small>{pb.kind==='遭遇'?'路遇危险，可战可避':'任务时限在即，需给出回应'}</small></div><p className="fork-title">{pb.title}</p><p className="fork-text">{pb.desc}{pb.reward?`完成报酬 ${money(pb.reward)}。`:''}</p><div className="fork-actions">{!running&&<><button className="primary" onClick={()=>{const r=perform(game,'battle-accept','');if(r.error){setMessage(r.error);return}if(!commit(r.state,game,true))return;setMessage('战斗开始，已为你打开冒险界面。');setModal(false);onEnterBattle()}}>接受 · 迎战</button><button onClick={()=>{const r=perform(game,'battle-flee','');if(r.error){setMessage(r.error);return}if(!commit(r.state,game,true))return;setMessage('你选择暂避锋芒。可继续模拟。');setModal(true)}}>逃跑</button></>}</div></div>:null;
 const battleWonBlock=()=>!running&&game.battle?.done&&game.battle.won&&!pb&&!isFork&&game.hosting?.active?<div className="fork-prompt battle-prompt"><div className="fork-head"><b>战斗胜利</b><small>经验与战利品已入账</small></div><p className="fork-title">下一程如何安排？</p><div className="fork-actions"><button className="primary" onClick={()=>{const next={...game,battle:null,hosting:{...game.hosting!,active:true,recovering:false,reason:''}};if(!commit(next,game,false))return;setModal(true);run(next)}}>继续模拟</button><button onClick={()=>{const next={...game,battle:null,hosting:{...game.hosting!,active:true,recovering:true,reason:'恢复至最佳状态后继续。'}};if(!commit(next,game,false))return;setModal(true);run(next)}}>恢复至最佳状态后继续</button><button onClick={()=>{const next={...game,battle:null,hosting:{...game.hosting!,active:false,recovering:false,reason:'你选择退出模拟，稍后再续。'}};if(!commit(next,game,false))return;setModal(false);setMessage('已退出模拟。')}}>退出模拟</button></div></div>:null;
 const replayModal=<div className="modal-backdrop" onClick={()=>{if(!running)stop()}}><div className="modal replay-modal" onClick={e=>e.stopPropagation()}><div className="replay-modal-head"><b>模拟进行中</b><span className={running?'pulse':''}/><button aria-label="关闭" onClick={stop}><ArrowRight size={16} className="rot90"/></button></div>{isFork&&!running&&forkBlock()}{pb&&!isFork&&battleBlock()}{!pb&&!isFork&&battleWonBlock()}<div className="replay-panel replay-modal-panel"><div className="replay-head"><b>重要时刻回放</b><span>播放速率</span>{rates.map(r=><button key={r} className={rate===r?'active':''} onClick={()=>pickRate(r)}>{r}×</button>)}<small className={replay.length?'':'hidden'}>{replay.length} 个时刻</small></div><div className="replay-list" ref={replayBox}>{replay.length===0?<p className="replay-empty">{running?'模拟进行中，重要时刻将出现在这里……':'暂无重要时刻'}</p>:replay.map((e,i)=><div className="replay-item" key={i}><small>{date(e.day)}</small><b>{e.title}</b><p>{e.text}</p></div>)}</div></div><div className="replay-modal-foot"><small>{message}</small><div className="replay-modal-btns">{running?<button className="primary" onClick={stop}><Pause size={16}/>停止模拟</button>:<button className="primary" onClick={()=>void run(game)}><Play size={16}/>继续模拟</button>}{!running&&!game.hosting?.active&&<button onClick={()=>setModal(false)}>关闭</button>}</div></div></div></div>;
 return <div className="hosting-panel">
 {isFork&&!running&&!modal&&forkBlock()}
 {pb&&!isFork&&!running&&!modal&&battleBlock()}
 <div className="hosting-status" role="status"><span className={running?'pulse':''}/><div><b>{running?'模拟进行中':game.hosting?.active?'模拟已准备':'模拟待命'}</b><small>{message}</small>{game.hosting&&<small>本次已处理 {game.hosting.completed} 步</small>}</div></div>
 <div className="save-actions">{running?<button className="primary" onClick={stop}><Pause size={16}/>停止模拟</button>:<button className="primary" onClick={start} disabled={game.dead||game.retired||!!(game.battle&&!game.battle.done)}><Play size={16}/>开始模拟</button>}{!running&&game.hosting?.active&&<button onClick={()=>void run(game)}>继续模拟</button>}<button className="recover-btn" onClick={recover}><HeartPulse size={16}/>恢复至最佳状态</button></div>
 <h4>事件倾向</h4><div className="hosting-temperaments">{temperaments.map(([value,label,detail])=><label key={value} className={temperament===value?'selected':''}><input type="radio" name="hosting-temperament" checked={temperament===value} onChange={()=>setTemperament(value)}/><b>{label}</b><small>{detail}</small></label>)}</div>
 {age(game)<adultAge(game.draft.race)&&<p className="hosting-help">当前角色尚未成年，工作与探索收入有限，模拟难以积累现金；请确保留足至少两周食宿的积蓄（模拟会在现金不足时自动暂停）。</p>}
 <details className="hosting-details"><summary>模拟安排</summary><div className="hosting-intro"><Shield size={28}/><div><h3>模拟安排</h3><p>自动平衡工作、探索与学习；事件会自动作答，期间不会打断。进行中的委托若已达标，会优先交付换取报酬。点「开始模拟」弹出回放窗口，点「停止」随时结束。</p></div></div></details>
 <details className="hosting-details"><summary>何时自动休息</summary><p className="hosting-help">体力低于设定值时休息；伤势较重（超过15）也会自动休息，重伤（超过30且付得起诊金）会优先就医。生命条件仅是濒死保护线：体力足够时，普通低生命仍会继续工作，只有接近死亡才停下休息。</p><div className="hosting-rest"><label><input type="checkbox" checked={staminaOn} onChange={e=>setStaminaOn(e.target.checked)}/><span>体力低于</span><input aria-label="体力阈值" type="number" min="0" max="100" value={stamina} disabled={!staminaOn} onChange={e=>setStamina(Number(e.target.value))}/></label><label><input type="checkbox" checked={hpOn} onChange={e=>setHpOn(e.target.checked)}/><HeartPulse size={16}/><span>生命濒死线低于</span><input aria-label="生命濒死线" type="number" min="1" max="10" value={hp} disabled={!hpOn} onChange={e=>setHp(Number(e.target.value))}/></label></div></details>
 <details className="hosting-details"><summary>自动事件选择规则</summary><div className="hosting-rules"><b>自动事件选择</b><p>优先选择可提升的最高熟练度技能；普通事件会跳过已达100的技能。出现突破事件时，优先选择可突破上限的对应选项。事件的现金、物品、声望、花费与受伤风险会按当前倾向一并评估。</p></div></details>
 {modal&&replayModal}
 </div>
}
