'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Play,Shield,Footprints,HeartPulse,BatteryCharging} from 'lucide-react';
import {hostedStep,weeklyLiving} from '../lib/hosting';
import {age,adultAge,money} from '../lib/game';
import type {Game,Hosting} from '../lib/game';

type Props={game:Game,slotId:string,onCommit:(next:Game,expected:Game,slot:string,history:boolean,revision:number)=>boolean,getRevision:()=>number};
const temperaments=[['adventure','冒险','接受风险，重视高额收益与突破机会'],['balanced','平和','优先熟练度与稳定收益，适度避险'],['cautious','谨慎','避开受伤与高花费，优先安全选项']] as const;

export default function HostingPanel({game,slotId,onCommit,getRevision}:Props){
 const existing=game.hosting;const [action,setAction]=useState<Hosting['action']>(existing?.action||'work'),[temperament,setTemperament]=useState<Hosting['temperament']>(existing?.temperament||'balanced'),[staminaOn,setStaminaOn]=useState(existing?.staminaBelow!==null&&existing?.staminaBelow!==undefined),[hpOn,setHpOn]=useState(existing?.hpBelow!==null&&existing?.hpBelow!==undefined),[stamina,setStamina]=useState(existing?.staminaBelow??35),[hp,setHp]=useState(Math.min(existing?.hpBelow??10,10)),[days,setDays]=useState(existing?.targetDays||180),[running,setRunning]=useState(false),[message,setMessage]=useState(existing?.reason||'尚未开始托管。');
 const serial=useRef(0),live=useRef(true),current=useRef(game),revision=useRef(getRevision());current.current=game;
 useEffect(()=>{live.current=true;return ()=>{live.current=false;serial.current++}},[]);
 useEffect(()=>{if(running&&game!==current.current){setRunning(false);setMessage('人物状态已变化，托管已停止。')}},[game,running]);
 const commit=(next:Game,base:Game,history:boolean)=>{if(!onCommit(next,base,slotId,history,revision.current)){setRunning(false);setMessage('存档已变化，请重新开始托管。');return false}revision.current=getRevision();current.current=next;return true};
 const config=():Hosting=>({action,temperament,staminaBelow:staminaOn?Math.max(0,Math.min(100,Math.round(stamina))):null,hpBelow:hpOn?Math.max(1,Math.min(10,Math.round(hp))):null,resting:false,forcedWork:false,targetDays:days,steps:2000,active:true,completed:existing?.completed||0,reason:'托管已启动。'});
 async function run(base:Game){const ticket=++serial.current;setRunning(true);const maxDays=Math.max(7,Math.min(36000,base.hosting?.targetDays||180));const maxSteps=2000;const startDay=base.day;let local=base;for(let step=0;step<maxSteps;step++){if(!live.current||ticket!==serial.current)return;const result=hostedStep(local);if(!commit(result.state,local,!result.error)){setRunning(false);return}local=result.state;setMessage(result.reason);if(result.error||!local.hosting?.active){setRunning(false);return}if(local.day-startDay>=maxDays)break;await new Promise(resolve=>setTimeout(resolve,80));}if(ticket===serial.current){const done=local.day-startDay;const label=done>=360?Math.floor(done/360)+'年'+((done%360)>=30?Math.floor((done%360)/30)+'个月':''):done>=30?Math.floor(done/30)+'个月':done+'天';const paused={...local,hosting:{...local.hosting!,active:false,reason:'本次已完成约'+label+'托管，请查看经历后继续。'}};commit(paused,local,false);setRunning(false);setMessage(paused.hosting.reason)}}
 function start(){if(game.dead||game.retired)return;const need=weeklyLiving(game)*2;if(game.cash<need){setMessage('现金不足两周食宿（约'+money(need)+'，当前'+money(game.cash)+'），托管不会开始。先手动「学习与帮忙」一两周，攒够生活费再来。');return}revision.current=getRevision();const planned={...game,hosting:config()};if(commit(planned,game,false))void run(planned)}
 function pause(){serial.current++;const base=current.current;if(base.hosting){const paused={...base,hosting:{...base.hosting,active:false,reason:'你暂停了托管。'}};commit(paused,base,false)}setRunning(false);setMessage('你暂停了托管。')}
 return <div className="hosting-panel"><div className="hosting-duration"><h4>托管时长</h4><p>每批执行约 <input aria-label="托管天数" type="number" min="7" max="36000" value={days} disabled={running} onChange={e=>setDays(Math.max(7,Math.min(36000,Number(e.target.value)||180)))}/> 天（默认180天≈半年）后自动暂停。按实际行动推进：工作7日/休息2日/探索3日算一步，到设定天数即停。</p></div>
 <div className="hosting-intro"><Shield size={28}/><div><h3>托管安排</h3><p>按设定重复学习与帮忙或探索；事件会自动作答，期间不会打断。进行中的委托若已达标，会优先交付换取报酬。</p></div></div>
 <div className="hosting-options"><label className={action==='work'?'selected':''}><input type="radio" name="hosting-action" checked={action==='work'} onChange={()=>setAction('work')}/><BatteryCharging size={18}/><span>学习与帮忙<small>稳定报酬与职业技能</small></span></label><label className={action==='explore'?'selected':''}><input type="radio" name="hosting-action" checked={action==='explore'} onChange={()=>setAction('explore')}/><Footprints size={18}/><span>探索周边<small>采集、收益与受伤风险</small></span></label></div>
 <h4>事件倾向</h4><div className="hosting-temperaments">{temperaments.map(([value,label,detail])=><label key={value} className={temperament===value?'selected':''}><input type="radio" name="hosting-temperament" checked={temperament===value} onChange={()=>setTemperament(value)}/><b>{label}</b><small>{detail}</small></label>)}</div>
 <h4>何时自动休息</h4><p className="hosting-help">体力低于设定值时休息；伤势较重（超过15）也会自动休息，重伤（超过30且付得起诊金）会优先就医。生命条件仅是濒死保护线：体力足够时，普通低生命仍会继续工作，只有接近死亡才停下休息。</p><div className="hosting-rest"><label><input type="checkbox" checked={staminaOn} onChange={e=>setStaminaOn(e.target.checked)}/><span>体力低于</span><input aria-label="体力阈值" type="number" min="0" max="100" value={stamina} disabled={!staminaOn} onChange={e=>setStamina(Number(e.target.value))}/></label><label><input type="checkbox" checked={hpOn} onChange={e=>setHpOn(e.target.checked)}/><HeartPulse size={16}/><span>生命濒死线低于</span><input aria-label="生命濒死线" type="number" min="1" max="10" value={hp} disabled={!hpOn} onChange={e=>setHp(Number(e.target.value))}/></label></div>
 {age(game)<adultAge(game.draft.race)&&<p className="hosting-help">当前角色尚未成年，工作与探索收入有限，托管难以积累现金；请确保留足至少两周食宿的积蓄（托管会在现金不足时自动暂停）。</p>}
 <div className="hosting-rules"><b>自动事件选择</b><p>优先选择可提升的最高熟练度技能；普通事件会跳过已达100的技能。出现突破事件时，优先选择可突破上限的对应选项。事件的现金、物品、声望、花费与受伤风险会按当前倾向一并评估。</p></div>
 <div className="hosting-status" role="status"><span className={running?'pulse':''}/><div><b>{running?'托管进行中':game.hosting?.active?'托管已准备':'托管待命'}</b><small>{message}</small>{game.hosting&&<small>本次已处理 {game.hosting.completed} 步</small>}</div></div>
 <div className="save-actions">{running?<button className="primary" onClick={pause}><Pause size={16}/>暂停托管</button>:<button className="primary" onClick={start} disabled={game.dead||game.retired}><Play size={16}/>开始托管</button>}{!running&&game.hosting?.active&&<button onClick={()=>void run(game)}>继续托管</button>}</div>
 </div>
}
