import {validLifeGoal,type LifeGoal} from './goal-types';
export const regions = [
 {name:'洛恩王国',sub:'河谷与王冠',town:'灰河镇',tags:'农业 · 手艺 · 骑士',desc:'麦田延伸至城堡脚下。行会、骑士与古老家族在这里交织。河流带来丰收，也将远方的消息带入小镇。',faction:'灰河行会',price:1},
 {name:'卡斯蒂亚帝国',sub:'石路与雄鹰',town:'瓦伦城',tags:'军旅 · 工程 · 政治',desc:'军团守望石砌大道，帝都的高塔投下漫长阴影。功绩、税籍和推荐信，决定许多大门是否向你敞开。',faction:'帝国军务厅',price:1.15},
 {name:'北境诸领',sub:'霜雪与誓言',town:'霜松堡',tags:'狩猎 · 生存 · 氏族',desc:'漫长冬季考验每一户人家。猎人穿过针叶林，领主在炉火前交换盟誓，储粮和朋友同样珍贵。',faction:'霜松盟誓会',price:1.2},
 {name:'阿尔玛自由城邦',sub:'海风与银币',town:'白帆港',tags:'贸易 · 航海 · 行会',desc:'帆影涌入港湾，市集用不同语言讨价还价。自由有价，而每一份契约都是新的起点。',faction:'白帆商会',price:1.3},
 {name:'圣辉教国',sub:'钟声与烛光',town:'晨钟镇',tags:'医疗 · 学识 · 信仰',desc:'钟声划分修院的一天。医者、学者和朝圣者走过石阶，信仰之中也有不同的答案。',faction:'晨钟慈善修会',price:.9},
 {name:'暮林边境',sub:'古木与低语',town:'苔桥村',tags:'药草 · 遗迹 · 魔法',desc:'古老树冠遮蔽遗忘的石碑。人类与精灵的道路在贸易站相遇，林深处仍有未解之事。',faction:'苔桥守林议会',price:1.1}
];
export const steps = [
 {key:'region',title:'选择你的出生地区',hint:'六片土地，六种生活的起点。出生不会决定你的一生。',options:regions.map(r=>r.name)},
 {key:'social',title:'你出生于怎样的阶层？',hint:'阶层影响资源与机会，但不会锁定你未来的职业。',options:['农奴','自由农民','城市贫民','工匠家庭','商人家庭','低阶贵族','大贵族旁支','骑士家庭','教会孤儿','魔法世家','边境猎户']},
 {key:'race',title:'你的血脉来自何处？',hint:'种族影响成年与衰老时间，不决定善恶。人类、兽人18岁成年，矮人25岁，精灵35岁。',options:['人类','精灵遗民','矮人','兽人']},
 {key:'identity',title:'你的名字将写在这里',hint:'名字和性别不影响机会或属性。',options:[]},
 {key:'age',title:'故事开始时，你多大？',hint:'幼年以家庭和教育为主；成年后开启职业、产业与婚姻。',options:['童年 · 8岁','少年 · 14岁','成年 · 适龄','壮年 · 40岁']},
 {key:'family',title:'谁与你一起长大？',hint:'家庭提供起点，也带来值得牵挂的人。',options:['双亲与手足','单亲抚养','祖辈照顾','修院养育','独自成长']},
 {key:'wealth',title:'家中留给你多少余裕？',hint:'这是个人可支配资金，不等于家族的全部财产。',options:['拮据 · 1银','温饱 · 8银','宽裕 · 30银']},
 {key:'education',title:'你最早接受了什么教育？',hint:'教育给予入门技能。高深学问仍需导师与长期练习。',options:['田间劳动','工坊学艺','商铺算账','教会识字','骑士启蒙','山林求生']},
 {key:'personality',title:'什么最接近你的性格？',hint:'性格带来小幅属性差异，你仍能做出不同选择。',options:['坚毅','好奇','谨慎','亲和','果敢','务实']},
 {key:'potential',title:'你与以太之间有何联系？',hint:'潜质不等于法术。低魔世界里，普通人的一生也足够辽阔。',options:['未显现','微弱共鸣','罕见亲和']},
 {key:'childhood',title:'哪段往事一直留在心里？',hint:'一个小小的起点，留下真实的技能与关系。',options:['帮助邻人收获','捡到残缺旧书','随商队远行','在森林中迷路','照料患病亲人','旁观骑士比武']},
 {key:'goal',title:'你希望如何度过这一生？',hint:'目标可以指引你，也可以在生活中改变。没有唯一正确的结局。',options:['安稳生活，守护家庭','成为受人尊敬的匠人','建立自己的商号','探索被遗忘的遗迹','成为受封骑士','理解以太的秘密']}
];
export const skillNames=['剑术','盾牌','弓术','骑术','潜行','锻造','炼金','医术','识字','贸易','礼仪','指挥','生存','元素','治疗','结界','占卜'];
export const attrNames=['力量','敏捷','体质','智力','感知','意志','魅力','幸运'];
export const difficulties:Record<string,{living:number,income:number,risk:number,hurt:number,desc:string}>={
 '简单':{living:12,income:1.25,risk:10,hurt:.65,desc:'每日基础食宿12铜，收入提高25%，判定更宽容，伤害降低35%。'},
 '中等':{living:20,income:1,risk:0,hurt:1,desc:'每日基础食宿20铜，标准收入与风险，适合体验完整人生。'},
 '困难':{living:28,income:.9,risk:-10,hurt:1.3,desc:'每日基础食宿28铜，收入降低10%，判定更难，伤害提高30%。'},
 '地狱':{living:36,income:.8,risk:-20,hurt:1.7,desc:'每日基础食宿36铜，收入降低20%，判定严苛，伤害提高70%。'}
};
export function difficulty(s:Game){return difficulties[s.mode]||difficulties['中等']}
export const jobs=[{name:'农工',skill:'生存',base:42},{name:'铁匠',skill:'锻造',base:52},{name:'商贩',skill:'贸易',base:56},{name:'猎人',skill:'弓术',base:50},{name:'医者',skill:'医术',base:48},{name:'守卫',skill:'剑术',base:50},{name:'学者',skill:'识字',base:48},{name:'法师',skill:'元素',base:65}];
export type Draft=Record<string,string>;
export type Entry={day:number,title:string,text:string,changes:string[]};
export type NPC={id:string,name:string,role:string,trust:number,affinity:number,last:number,age:number,alive:boolean};
export type Item={name:string,count:number,weight:number,durability:number,slot:string};
export type Quest={id:number,title:string,skill:string,need:number,reward:number,due:number,status:string};
export type Estate={name:string,level:number,condition:number,workers:number,revenue:number};
export type Hosting={action:'work'|'explore',temperament:'adventure'|'balanced'|'cautious',staminaBelow:number|null,hpBelow:number|null,staminaRecoverTo?:number|null,hpRecoverTo?:number|null,resting?:boolean,active:boolean,completed:number,reason:string};
export type Game={aiGoal?:LifeGoal,hosting?:Hosting,version:1,id:string,draft:Draft,day:number,ageStart:number,region:number,birthRegion:number,job:number,rank:number,seed:number,turn:number,hp:number,stamina:number,spirit:number,mana:number,maxMana:number,hunger:number,injury:number,cash:number,debt:number,debtDue:number,attributes:Record<string,number>,skills:Record<string,number>,items:Item[],npcs:NPC[],quests:Quest[],fame:number[],crime:number,estate:Estate|null,spouse:string|null,children:{name:string,born:number}[],known:number[],event:string|null,seen:Record<string,number>,log:Entry[],mode:string,dead:boolean,retired:boolean,generation:number,heir:boolean};
const clamp=(x:number,min=0,max=100)=>Math.min(max,Math.max(min,x));
export function adultAge(race:string){return race==='精灵遗民'?35:race==='矮人'?25:18}
export function age(s:Game){return s.ageStart+Math.floor(s.day/360)}
export function date(day:number){return `${742+Math.floor(day/360)}年 ${Math.floor(day%360/30)+1}月 ${day%30+1}日`}
export function season(day:number){return ['春','夏','秋','冬'][Math.floor(day%360/90)]}
export function money(c:number){return `${Math.floor(c/10000)?Math.floor(c/10000)+'金 ':''}${Math.floor(c%10000/100)}银 ${c%100}铜`}
export function jobTitle(s:Game){return age(s)<adultAge(s.draft.race)?'成长中的孩子':(s.rank>=3?'资深':s.rank>=2?'正式':s.rank===1?'见习':'')+jobs[s.job].name}
export function maxLoad(s:Game){return 15+s.attributes['力量']*2}
export function weight(s:Game){return s.items.reduce((v,i)=>v+i.count*i.weight,0)}
function rand(s:Game){s.seed=(Math.imul(1664525,s.seed)+1013904223)>>>0;return s.seed/4294967296}
function gain(s:Game,k:string,n:number,breakthrough=false){s.skills[k]=clamp((s.skills[k]||0)+n,0,breakthrough?120:100)}
function addItem(s:Game,name:string,n:number,weight=.2,slot='材料'){let i=s.items.find(i=>i.name===name);if(i)i.count+=n;else s.items.push({name,count:n,weight,durability:100,slot});s.items=s.items.filter(i=>i.count>0)}
function entry(s:Game,title:string,text:string,changes:string[]=[]){s.log.push({day:s.day,title,text,changes});}
export function createGame(d:Draft,mode='中等'):Game{
 const region=Math.max(0,regions.findIndex(r=>r.name===d.region));const attrs=Object.fromEntries(attrNames.map(k=>[k,10]));attrs[({坚毅:'意志',好奇:'智力',谨慎:'感知',亲和:'魅力',果敢:'力量',务实:'体质'} as Record<string,string>)[d.personality]||'幸运']+=2;
 if(d.race==='矮人')attrs.体质+=2;if(d.race==='精灵遗民')attrs.感知+=2;if(d.race==='兽人')attrs.力量+=2;
 const ageStart=d.age.includes('8岁')?8:d.age.includes('14岁')?14:d.age.includes('40岁')?40:adultAge(d.race);const skills=Object.fromEntries(skillNames.map(k=>[k,0]));const edu=steps[7].options.indexOf(d.education);const initialSkill=['生存','锻造','贸易','识字','剑术','弓术'][Math.max(0,edu)];skills[initialSkill]=12;skills.生存+=4;
 const child=steps[10].options.indexOf(d.childhood);skills[['生存','识字','贸易','生存','医术','礼仪'][Math.max(0,child)]]+=5;
 const s:Game={version:1,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),draft:{...d},day:0,ageStart,region,birthRegion:region,job:[0,1,2,6,5,3][Math.max(0,edu)],rank:0,seed:(Date.now()>>>0)||1,turn:0,hp:100,stamina:100,spirit:100,mana:0,maxMana:d.potential==='罕见亲和'?40:d.potential==='微弱共鸣'?20:0,hunger:0,injury:0,cash:d.wealth.startsWith('宽裕')?3000:d.wealth.startsWith('温饱')?800:100,debt:0,debtDue:0,attributes:attrs,skills,items:[{name:'粗布衣',count:1,weight:1,durability:100,slot:'护甲'},{name:'黑面包',count:3,weight:.25,durability:100,slot:'消耗'},{name:'旧短刀',count:1,weight:.8,durability:70,slot:'武器'}],npcs:[{id:'friend',name:['米拉','塞维尔','托林','莉娅','安瑟','伊芙'][region],role:'旧识 · 同龄人',trust:18,affinity:20,last:-10,age:ageStart,alive:true},{id:'mentor',name:['奥伦','维克多','格伦','达莉亚','赛琳','林恩'][region],role:'当地前辈 · 潜在导师',trust:8,affinity:10,last:-10,age:ageStart+24,alive:true}],quests:[],fame:[0,0,0,0,0,0],crime:0,estate:null,spouse:null,children:[],known:[region],event:null,seen:{},log:[],mode,dead:false,retired:false,generation:1,heir:false};
 s.mana=s.maxMana;if(d.family!=='独自成长')s.npcs.push({id:'family',name:d.family==='祖辈照顾'?'祖母 艾妲':d.family==='修院养育'?'抚养者 贝伦':'家人 罗温',role:'家族 · '+d.family,trust:65,affinity:70,last:-10,age:ageStart+(d.family==='祖辈照顾'?48:23),alive:true});
 entry(s,'第一章 · 一生的起点',`${regions[region].town}的晨光落在窗沿。${d.name}，你带着「${d.childhood}」的记忆，开始了${ageStart}岁这一年的生活。${d.social}给了你一个起点，往后的路还没有名字。`,['人生目标：'+d.goal]);return s;
}
export type Choice={label:string,detail:string,days:number,cost?:number,skill?:string,difficulty?:number,reward?:number,trust?:number,fame?:number,item?:string,hurt?:number,follow?:string,breakthrough?:boolean};
export type Event={id:string,title:string,text:string,kind:string,choices:Choice[],condition?:(s:Game)=>boolean};
const choice=(label:string,detail:string,days:number,other:Partial<Choice>={}):Choice=>({label,detail,days,...other});
const baseEvents:Event[]=[
 {id:'harvest',kind:'邻里',title:'需要帮手的麦田',text:'昨夜的雨将部分麦秆压倒。邻居在田埂上向你招手，请你在天气转坏前搭一把手。',choices:[choice('一起抢收','2日 · 生存实践 · 有报酬',2,{skill:'生存',reward:90,trust:4}),choice('组织邻里互助','1日 · 礼仪考验',1,{skill:'礼仪',difficulty:8,fame:3,trust:6}),choice('继续自己的生活','不耗时',0)]},
 {id:'book',kind:'学识',title:'书摊上的残页',text:'旧货商摊开一本线装册子，里面画着水车和陌生符号。你可以尝试辨认，也可以先带回去慢慢研读。',choices:[choice('买下旧书','40铜 · 识字练习',1,{cost:40,item:'残页手稿',skill:'识字'}),choice('当场辨认文字','1日 · 识字考验',1,{skill:'识字',difficulty:12,reward:20}),choice('记住摊位，暂且离开','不耗时',0)]},
 {id:'caravan',kind:'市井',title:'远方的车铃',text:'一支商队停在城门外。领队需要人手整理货单，也愿意用一顿饭的时间讲讲外面的道路。',choices:[choice('帮忙清点货物','1日 · 贸易实践 · 60铜报酬',1,{skill:'贸易',reward:60}),choice('请领队吃饭打听道路','15铜 · 1日 · 生存知识',1,{cost:15,skill:'生存',follow:'商队说北方的道路泥泞，冬季之前还会有一趟运粮车。'}),choice('目送商队离开','不耗时',0)]},
 {id:'wedding',kind:'人生',title:'广场上的婚礼',text:'面包香与乐声飘出广场。旧识把你拉到长桌旁，邻里正在为一对新人庆祝。',choices:[choice('带上礼物参加','25铜 · 1日 · 关系增进',1,{cost:25,trust:8}),choice('帮忙布置场地','1日 · 少量报酬与人情',1,{reward:30,trust:4}),choice('送上祝福后离开','不耗时',0)]},
 {id:'apprentice',kind:'职业',title:'工坊门前的告示',text:'工坊正在招募学徒。前辈愿意给你一次试工机会，但会如实指出手艺上的不足。',condition:s=>s.rank===0,choices:[choice('接受试工','2日 · 锻造考验',2,{skill:'锻造',difficulty:5,reward:110,trust:7}),choice('请教入门方法','1日 · 锻造实践',1,{skill:'锻造',trust:3}),choice('另寻方向','不耗时',0)]},
 {id:'herbs',kind:'探索',title:'雨后的药草',text:'林缘生出一簇银叶草。药师提醒你，其中混着外观相似的苦茎，需要仔细辨别。',choices:[choice('辨识后采集','1日 · 医术考验 · 草药',1,{skill:'医术',difficulty:5,item:'止血草',reward:25}),choice('跟着药师学习','20铜 · 1日 · 医术练习',1,{cost:20,skill:'医术'}),choice('不采陌生植物','不耗时',0)]},
 {id:'dispute',kind:'市井',title:'秤盘的两端',text:'摊主与顾客为一袋盐争执。没有人愿意先退让，围观的人越来越多。',choices:[choice('提议重新称重','1日 · 贸易考验',1,{skill:'贸易',difficulty:5,fame:3}),choice('劝双方心平气和','1日 · 礼仪考验',1,{skill:'礼仪',difficulty:10,trust:5}),choice('不参与纠纷','不耗时',0)]},
 {id:'wolf',kind:'荒野',title:'篱笆外的足迹',text:'羊圈附近发现大型动物的脚印。牧人不敢贸然追赶，想知道它是否仍在附近。',choices:[choice('沿林缘追踪','2日 · 生存考验 · 受伤风险',2,{skill:'生存',difficulty:15,reward:130,hurt:12,fame:3}),choice('帮助加固围栏','1日 · 40铜材料 · 安全',1,{cost:40,trust:7,skill:'锻造'}),choice('把消息告知守卫','1日 · 地方声望',1,{fame:1})]},
 {id:'mentor',kind:'关系',title:'一碗仍然温热的汤',text:'前辈这几日没有出门。门内传来咳嗽声，桌上堆着尚未完成的活计。',condition:s=>s.npcs.some(n=>n.id==='mentor'&&n.alive),choices:[choice('照料并处理杂务','2日 · 医术实践 · 信任',2,{skill:'医术',trust:9}),choice('请医者上门','80铜 · 1日 · 信任',1,{cost:80,trust:12}),choice('托人捎去问候','不耗时',0)]},
 {id:'river',kind:'探索',title:'被冲坏的木桥',text:'河水冲松了桥板。一个车夫在桥头犹豫，货物的交付期限近在眼前。',choices:[choice('帮忙修桥','2日 · 锻造考验',2,{skill:'锻造',difficulty:8,reward:120,fame:3}),choice('寻找可走的浅滩','1日 · 生存考验',1,{skill:'生存',difficulty:12,reward:60,hurt:8}),choice('提醒来人绕路','1日 · 地方声望',1,{fame:1})]},
 {id:'festival',kind:'人生',title:'一年一度的集市',text:'彩带挂上街角，远方艺人带来故事与乐曲。今天有许多人愿意坐下来听你说话。',choices:[choice('与旧识共度节日','35铜 · 1日 · 信任',1,{cost:35,trust:10}),choice('摆摊试试生意','2日 · 贸易考验',2,{skill:'贸易',difficulty:5,reward:145}),choice('参加比武表演','1日 · 剑术考验 · 轻伤风险',1,{skill:'剑术',difficulty:15,reward:95,hurt:8,fame:3}),choice('安静地过一天','不耗时',0)]},
 {id:'ruin',kind:'遗迹',title:'青苔下的石阶',text:'山坡露出一段古老阶梯。入口附近没有新鲜足迹，石门上的字似乎是一则警示。',choices:[choice('拓印并研究铭文','2日 · 识字考验',2,{skill:'识字',difficulty:18,item:'遗迹拓片',fame:2}),choice('带绳索进行浅层调查','35铜 · 2日 · 生存考验 · 高风险',2,{cost:35,skill:'生存',difficulty:22,reward:220,hurt:25,item:'古代碎片'}),choice('标记入口，准备后再来','不耗时',0)]},
 {id:'ether',kind:'以太',title:'烛焰短暂地偏转',text:'读书时，烛焰在无风的屋内向你倾斜。巡游学者愿意帮助你分辨这是否与以太有关。',condition:s=>s.maxMana>0,choices:[choice('接受基础指导','90铜 · 3日 · 元素练习',3,{cost:90,skill:'元素',item:'符文练习板'}),choice('自己记录变化','2日 · 识字实践',2,{skill:'识字'}),choice('暂不追究','不耗时',0)]},
 {id:'guard',kind:'军旅',title:'守卫队的缺额',text:'城门守卫正在安排轮值。他们需要可靠的人，先从搬运物资和练习队列做起。',condition:s=>age(s)>=adultAge(s.draft.race),choices:[choice('参加巡逻试训','3日 · 剑术实践 · 工钱',3,{skill:'剑术',reward:150,fame:2}),choice('协助整理补给','2日 · 指挥实践',2,{skill:'指挥',reward:95}),choice('婉拒邀请','不耗时',0)]},
 {id:'tax',kind:'地方',title:'税吏来访',text:'税吏在广场公布新的道路维修摊派。居民可以提出意见，也可以参与工程抵扣部分费用。',choices:[choice('承担一份道路修缮','2日 · 锻造练习 · 声望',2,{skill:'锻造',fame:3,reward:75}),choice('提交合理的分摊建议','1日 · 礼仪考验',1,{skill:'礼仪',difficulty:15,fame:5}),choice('阅读或听取公告','1日 · 识字练习',1,{skill:'识字'})]},
 {id:'storm',kind:'季节',title:'风暴将至',text:'天空低垂，店家开始收起棚布。邻近住户的屋顶还没补完，今晚可能漏雨。',choices:[choice('帮邻居修补屋顶','1日 · 锻造实践',1,{skill:'锻造',trust:6,reward:30}),choice('出钱买防雨布','30铜 · 1日 · 信任',1,{cost:30,trust:8}),choice('检查自己的行囊','1日 · 生存实践',1,{skill:'生存'})]},
 {id:'letter',kind:'关系',title:'从远方寄来的信',text:'熟人托人送来一封信，讲述在外地工作的见闻。他请你在方便时写一封回信。',choices:[choice('亲手写回信','1日 · 识字实践 · 信任',1,{skill:'识字',trust:4}),choice('请书记员代笔','15铜 · 1日 · 信任',1,{cost:15,trust:5}),choice('先把信收好','不耗时',0)]},
 {id:'duel',kind:'军旅',title:'练武场的邀请',text:'一位年轻守卫邀你以木剑切磋。旁边有人围观，胜负之外，分寸也会被记住。',condition:s=>s.skills.剑术>=10,choices:[choice('点到为止地切磋','1日 · 剑术考验 · 轻伤风险',1,{skill:'剑术',difficulty:14,fame:4,hurt:8}),choice('请对方指点步法','1日 · 剑术实践',1,{skill:'剑术',trust:2}),choice('婉拒，留待下次','不耗时',0)]},
 {id:'price',kind:'商业',title:'盐价上涨的传闻',text:'两位商人对粮船是否延期各执一词。有人正在囤货，但谁也没见过港口的正式通告。',choices:[choice('核查货单与消息','2日 · 贸易考验',2,{skill:'贸易',difficulty:12,reward:100}),choice('按需采购，不作投机','1日 · 贸易实践',1,{skill:'贸易'}),choice('略过这条传闻','不耗时',0)]},
 {id:'charity',kind:'信仰',title:'医院里的空床单',text:'慈善修会正在募集干净布料和帮手。负责的修士并不问你的信仰，只问你是否愿意帮忙。',choices:[choice('协助照顾病人','2日 · 医术练习',2,{skill:'医术',fame:3,trust:4}),choice('捐赠布料','50铜 · 1日 · 声望',1,{cost:50,fame:4}),choice('将消息转告邻里','1日 · 礼仪练习',1,{skill:'礼仪'})]},
 {id:'winter',kind:'季节',title:'第一场雪',text:'薄雪落在柴堆上。街坊开始盘算储粮，远行的人要重新考虑道路是否可靠。',condition:s=>season(s.day)==='冬',choices:[choice('帮助劈柴储粮','2日 · 生存实践 · 工钱',2,{skill:'生存',reward:100}),choice('照看独居邻人','1日 · 信任',1,{trust:7}),choice('修补冬衣','1日 · 锻造实践',1,{skill:'锻造'})]},
 {id:'guild',kind:'职业',title:'行会的公开考核',text:'行会打开院门，让有经验的人展示作品。评审既看技艺，也看你是否能承担承诺。',condition:s=>s.skills[jobs[s.job].skill]>=25,choices:[choice('展示工艺作品','2日 · 锻造考验',2,{skill:'锻造',difficulty:18,fame:6,reward:150}),choice('讲解契约与贸易方案','2日 · 贸易考验',2,{skill:'贸易',difficulty:18,fame:6,reward:150}),choice('旁听他人的经验','1日 · 礼仪实践',1,{skill:'礼仪'})]},
 {id:'orphan',kind:'人生',title:'修院的募集',text:'修院正在为失去照料的孩子筹措伙食。账目摆在门口，每一笔捐款都有去处。',choices:[choice('捐出一份伙食钱','40铜 · 1日 · 声望',1,{cost:40,fame:3}),choice('教孩子基础知识','2日 · 识字实践',2,{skill:'识字',trust:5}),choice('帮助搬运粮食','1日 · 生存实践',1,{skill:'生存',fame:1})]},
 {id:'dragon',kind:'传闻',title:'山口的巨影',text:'酒馆里有人说见到翼影掠过山口。猎人没有附和，只拿出一片异常的焦木。没有人能确认那是什么。',condition:s=>s.turn>18,choices:[choice('向猎人核实细节','2日 · 生存考验',2,{skill:'生存',difficulty:25,item:'焦木样本',follow:'猎人只确认山口有高温灼痕。是否与龙有关，仍缺乏证据。'}),choice('记录传闻，拒绝添油加醋','1日 · 识字实践',1,{skill:'识字'}),choice('继续眼前的生活','不耗时',0)]},
 {id:'kitten',kind:'童年',title:'墙头的小猫',text:'一只小猫困在雨后湿滑的墙头，叫声又细又急。你看见了它，周围也有人走过，但没有人肯为它停下来。',condition:s=>age(s)<adultAge(s.draft.race),choices:[choice('踮脚爬上去把它抱下来','1日 · 生存考验 · 擦伤风险',1,{skill:'生存',difficulty:10,reward:30,trust:3,hurt:6,follow:'小猫跳进邻家的院子，主人却记下了你的名字。'}),choice('搬来木箱垫脚，请路人搭手','1日 · 信任',1,{trust:5}),choice('在墙根放一点面包屑','不耗时',0)]},
 {id:'oldroad',kind:'荒野',title:'岔路口的旧路牌',text:'林间岔路口立着一块褪色的路牌，指向一条地图上没有标注的旧道。青草几乎掩住了路面，但隐约有车辙压过的痕迹。',choices:[choice('沿旧道探查废弃驿站','2日 · 生存考验 · 轻伤风险',2,{skill:'生存',difficulty:12,reward:80,item:'止血草',hurt:8,follow:'驿站的木梁早已朽坏，但你找到了几件还能用的旧物。'}),choice('拓下路牌上的刻字','1日 · 识字实践',1,{skill:'识字'}),choice('记住这个位置，以后再来','不耗时',0)]},
 {id:'tavern',kind:'市井',title:'酒馆里的半盏灯',text:'入夜后，酒馆里仍坐着几位远道而来的行商。壁炉的火光映着货单与旧靴，有人愿意说说话，也有人只是来歇脚。',condition:s=>age(s)>=adultAge(s.draft.race),choices:[choice('与行商攀谈路上的见闻','1日 · 贸易实践',1,{skill:'贸易',follow:'行商提起北方商路改道，入冬前还有一趟运盐车经过此地。'}),choice('请全桌喝一轮麦酒','30铜 · 1日 · 声望',1,{cost:30,fame:2,trust:4}),choice('只安静地听完一曲琴','1日 · 礼仪实践',1,{skill:'礼仪'})]},
 {id:'well',kind:'地方',title:'井边的绳结',text:'清晨的井台上围了几个人。辘轳的绳子磨得快要断开，取水的人排成一队，谁也不敢用劲。',choices:[choice('修理辘轳与井绳','1日 · 锻造考验',1,{skill:'锻造',difficulty:8,reward:50,fame:2}),choice('替几户人家把水缸打满','1日 · 体力活 · 少量报酬',1,{reward:35,trust:3}),choice('提醒大家小心湿滑的井台','1日 · 礼仪实践',1,{skill:'礼仪'})]},
 {id:'sheep',kind:'农事',title:'越过篱笆的羊',text:'邻人的羊群在昨夜拱开篱笆，跑进了坡后的灌木丛。牧人正急得团团转，说再找不回来，家里的冬粮就要打折扣。',choices:[choice('循蹄印与咩声寻找','1日 · 生存考验',1,{skill:'生存',difficulty:6,reward:55,fame:2,follow:'你把羊群赶回栅栏，牧人几乎要给你行一个礼。'}),choice('帮忙把篱笆重新扎牢','1日 · 锻造实践',1,{skill:'锻造',trust:4}),choice('指出羊群的方向后告辞','不耗时',0)]},
 {id:'coldnight',kind:'季节',title:'寒夜敲门声',text:'风雪把夜色压得很低。门忽然被敲响，门外站着一位裹紧旧斗篷的旅人，说前头的桥被雪掩了，想借宿一晚。',condition:s=>season(s.day)==='冬',choices:[choice('开门让他烤火借宿','1日 · 信任',1,{trust:6,follow:'旅人离开前留下一句忠告：今年北路的雪来得比往年早，储粮要多备一成。'}),choice('送他热食与一捆柴','30铜 · 1日 · 信任',1,{cost:30,trust:8}),choice('隔着门指给他驿站的方向','不耗时',0)]},
 {id:'ledger',kind:'商业',title:'算错的账目',text:'杂货铺的老板对着账本发愁：这个月的收支怎么也对不上，又不敢随便写在账册上。他认得你，说你会写字、算数。',choices:[choice('当面把账目复核一遍','1日 · 贸易考验',1,{skill:'贸易',difficulty:10,reward:90,fame:3,follow:'你找到了三处错账。老板重新誊写后，把酬金数了又数才递给你。'}),choice('借走旧账本回去细看','1日 · 识字实践',1,{skill:'识字'}),choice('提醒他请行会的书记员','1日 · 礼仪实践',1,{skill:'礼仪'})]},
 {id:'sickchild',kind:'家庭',title:'发烧的孩子',text:'家里的孩子夜里发起烧来，额头烫得吓人。医者住在镇子的另一头，这个时辰未必还醒着。',condition:s=>s.children.length>0,choices:[choice('用凉水与布巾整夜照护','2日 · 医术实践',2,{skill:'医术',follow:'天亮时热度退了下去，孩子又有了精神，缠着你要听故事。'}),choice('连夜去请医者上门','120铜 · 1日',1,{cost:120,follow:'医者诊过脉，留下药方。钱花得值得，孩子很快退了烧。'}),choice('与家人轮流守着','2日 · 信任',2,{trust:4})]},
 {id:'ether_echo',kind:'以太',title:'梦境中的回廊',text:'你梦见一道由光构成的回廊，尽头有模糊的低语，像是对着你的名字。醒来时，掌心的温度比平时高了一点。',condition:s=>s.maxMana>0,choices:[choice('把梦境逐字写成手记','1日 · 识字实践',1,{skill:'识字',follow:'文字留住了梦的形状。日后对照，或许能看出门道。'}),choice('循着记忆试着引导以太','1日 · 元素实践',1,{skill:'元素'}),choice('喝口水，当作寻常的梦','不耗时',0)]},
 {id:'ruin_trail',kind:'遗迹',title:'残片上的新痕',text:'你之前带回的遗迹残片上，出现了一道新的浅痕，切口干净得不像是自然风化。有人在你之后去过那座石阶。',condition:s=>s.seen['ruin']!==undefined,choices:[choice('沿新痕迹深入调查','2日 · 生存考验 · 高风险',2,{skill:'生存',difficulty:20,reward:160,item:'古代碎片',hurt:15,follow:'石阶深处，一扇半掩的石门后露出更古老的刻痕。你记下位置，退了出来。'}),choice('把发现告诉巡游学者','1日 · 识字实践',1,{skill:'识字',fame:3}),choice('暂时按捺好奇，等待时机','不耗时',0)]}
];
const masteryEvents:Event[]=skillNames.map(skill=>({id:'mastery-'+skill,kind:'突破',title:skill+'的瓶颈',text:`你在「${skill}」上已经走得很远。一次少见的机缘让你看见常规练习之外的道路，是否接受这次真正的考验？`,condition:s=>s.skills[skill]>=100&&s.skills[skill]<120,choices:[choice('接受突破考验','2日 · 突破上限 · '+skill,2,{skill,difficulty:22,breakthrough:true,follow:'这次经历撬开了原本坚固的瓶颈。你对技艺的理解跨过了常规训练的边界。'}),choice('记录心得，等待准备更充分','1日 · 不消耗突破机会',1,{follow:'你没有仓促踏入考验，而是把感悟认真记下。'})]}));
export const events:Event[]=[...baseEvents,...masteryEvents];
function advance(s:Game,days:number,changes:string[]){
 const before=s.day;const beforeAge=age(s);s.day+=days;
 const living=Math.round(days*(difficulty(s).living+s.children.filter(c=>(s.day-c.born)/360<adultAge(s.draft.race)).length*8)*regions[s.region].price);const paid=Math.min(s.cash,living);s.cash-=paid;
 if(living>paid){s.hunger=clamp(s.hunger+Math.ceil((living-paid)/10));changes.push('生活费不足，饥饿上升');}else{s.hunger=clamp(s.hunger-days*3)}
 if(days)changes.push('食宿 −'+money(paid));if(s.hunger>=70)s.hp=clamp(s.hp-Math.ceil(days*1.5));
 for(let month=Math.floor(before/30)+1;month<=Math.floor(s.day/30);month++){
  if(s.estate){const e=s.estate;const gross=Math.round((250+e.level*150+e.workers*60)*(e.condition/100)*(season(month*30)==='冬'?.8:1));const upkeep=100+e.workers*35;const net=gross-upkeep;s.cash=Math.max(0,s.cash+net);e.revenue=net;e.condition=clamp(e.condition-5);changes.push(e.name+'月结 '+(net>=0?'+':'')+money(Math.abs(net)));}
  if(s.debt&&s.day>s.debtDue){s.debt+=Math.ceil(s.debt*.03);s.fame[s.region]-=1;changes.push('债务逾期：追加3%利息，地方信用下降');s.debtDue+=30;}
 }
 s.quests.forEach(q=>{if(q.status==='进行中'&&s.day>q.due){q.status='已逾期';s.fame[s.region]-=2;changes.push('委托逾期：'+q.title)}});
 if(age(s)>beforeAge){changes.push('年龄 '+(age(s)-beforeAge)+'岁');const years=age(s)-beforeAge;s.npcs.forEach(n=>{if(n.alive){n.age+=years;if(n.age>(s.draft.race==='精灵遗民'?185:s.draft.race==='矮人'?115:85)&&rand(s)<.15*years){n.alive=false;changes.push(n.name+'离世');if(s.spouse===n.id)s.spouse=null}}});const threshold=s.draft.race==='精灵遗民'?160:s.draft.race==='矮人'?90:60;if(age(s)>threshold){s.hp=clamp(s.hp-years*5);s.injury=clamp(s.injury+years);if(age(s)>threshold+25&&rand(s)<.16*years)s.dead=true}}
 if(s.hp<=0)s.dead=true;
}
export function perform(original:Game,action:string,arg=''): {state:Game,error?:string}{
 const s:Game=structuredClone(original);if(s.dead||s.retired)return {state:original,error:'这段人生已经结束，请选择继承或开始新人生。'};
 const isAdult=age(s)>=adultAge(s.draft.race);const changes:string[]=[];let days=1,title='',text='';const cost=(n:number)=>{if(s.cash<n)return false;s.cash-=n;changes.push('支出 −'+money(n));return true};const fail=(e:string)=>({state:original,error:e});
 if(s.event&&action!=='event')return fail('请先回应眼前的事件，或选择事件中的离开选项。');
 if(action==='work'){days=7;title=isAdult?'一周的劳作':'成长中的一周';const j=jobs[s.job];const gross=Math.round((isAdult?j.base+s.rank*25+s.skills[j.skill]*.6:26)*days*difficulty(s).income);s.cash+=gross;gain(s,j.skill,s.skills[j.skill]<50?3:1);s.stamina=clamp(s.stamina-24);text=isAdult?`你在${regions[s.region].town}完成了一周${j.name}工作。熟悉的工具逐渐顺手，报酬来自实实在在的劳动。`:'你在家人或邻里照看下学习，做力所能及的杂务。年龄尚小，危险职业暂未开放。';changes.push('毛收入 +'+money(gross),j.skill+'熟练度提升');if(s.stamina<=5){s.hp=clamp(s.hp-8);s.injury=clamp(s.injury+5);changes.push('过劳：生命 −8，请休养')}}
 else if(action==='rest'){days=2;title='给自己一点时间';text='洗净衣物，吃些热食，让紧绷的身体慢慢放松。生活并不总要向前奔跑。';s.stamina=clamp(s.stamina+60);s.spirit=clamp(s.spirit+40);s.hp=clamp(s.hp+(s.injury>20?2:10));s.injury=clamp(s.injury-3);s.mana=clamp(s.mana+20,0,s.maxMana);changes.push('体力恢复','精神恢复','伤势缓慢恢复')}
 else if(action==='train'){if(!skillNames.includes(arg))return fail('请选择有效技能。');if(['元素','治疗','结界','占卜'].includes(arg)&&!s.maxMana)return fail('你尚未显现魔法潜质，不能直接练习施法。');if(s.skills[arg]>=85)return fail('你已精通这门技艺；进一步突破需要实际挑战。');const fee=s.skills[arg]>=40?140:45;if(!cost(fee))return fail('训练需'+money(fee)+'，请先准备费用。');days=7;title='把练习变成习惯';gain(s,arg,s.skills[arg]>=40?3:7);s.stamina=clamp(s.stamina-18);s.spirit=clamp(s.spirit-8);text=`你为「${arg}」留出了一周，记录错误，重复练习。${s.skills[arg]>=40?'前辈针对你的瓶颈进行指导。':'基础逐渐扎实。'}`;changes.push(arg+'熟练度提升');}
 else if(action==='job'){const i=Number(arg);if(!Number.isInteger(i)||!jobs[i])return fail('请选择有效职业。');if(!isAdult)return fail('成年后才能正式择业，目前可以学习相关技能。');if(i===7&&(!s.maxMana||s.skills.元素<15))return fail('法师职业需要魔法潜质和元素熟练度15。');s.job=i;s.rank=0;title='另一条道路';text=`你开始尝试${jobs[i].name}的工作。旧有知识依然保留，新工作需要重新证明自己。`;changes.push('职业：'+jobs[i].name);}
 else if(action==='promote'){if(!isAdult)return fail('成年后才能申请职业晋升。');if(s.rank>=3)return fail('你已达到本职业的资深阶段。');const need=[15,35,65][s.rank];if(s.skills[jobs[s.job].skill]<need)return fail('晋升需要'+jobs[s.job].skill+'熟练度'+need+'。');if(!cost(100*(s.rank+1)))return fail('考核费用不足。');s.rank++;days=3;title='被认可的技艺';text=`考核结束，你凭借积累取得了「${jobTitle(s)}」的身份，日后的工作报酬也会增加。`;s.fame[s.region]+=3;changes.push('职业晋升','地方声望 +3');}
 else if(action==='explore'){days=3;title='走出熟悉的街道';gain(s,'生存',4);s.stamina=clamp(s.stamina-22);text='你沿着林缘和旧道调查。足迹、废弃的营地和路人的话，让地图上的空白有了轮廓。';if(rand(s)<(.72+difficulty(s).risk/100)){addItem(s,'止血草',1);changes.push('止血草 +1');s.cash+=35;changes.push('采集收益 +35铜')}else{s.hp=clamp(s.hp-Math.round(12*difficulty(s).hurt));s.injury=clamp(s.injury+9);changes.push('擦伤：生命 −'+Math.round(12*difficulty(s).hurt))}changes.push('生存熟练度 +4');}
 else if(action==='social'){const n=s.npcs.find(n=>n.id===arg&&n.alive);if(!n)return fail('此人目前无法与你交谈。');if(s.day-n.last<5)return fail('你们刚刚相聚，过几天带着新的经历再来吧。');n.last=s.day;n.trust=clamp(n.trust+6);n.affinity=clamp(n.affinity+5);s.spirit=clamp(s.spirit+10);title='有人记得你的近况';text=`你和${n.name}聊起近来的生活。${n.role.includes('导师')?'前辈愿意听你讲述学习上的困难。':'对方也有自己的打算，你们交换了近况。'}`;changes.push(n.name+'信任 +6','亲近 +5');}
 else if(action==='marry'){const n=s.npcs.find(n=>n.id==='friend');if(!isAdult||!n||n.age<adultAge(s.draft.race))return fail('双方成年后才能讨论婚姻。');if(s.spouse)return fail('你已有配偶。');if(!n.alive||n.trust<65||n.affinity<60)return fail('婚姻需要长期相处：旧识信任65、亲近60。');if(!cost(600))return fail('简朴婚礼与家庭准备需要6银。');s.spouse=n.id;n.role='配偶 · 共同生活';days=3;title='两个人的家';text=`你与${n.name}认真讨论了生活和未来。在亲友见证下，你们决定共同承担往后的日子。`;changes.push('建立家庭');}
 else if(action==='adopt'){if(!isAdult||!s.spouse)return fail('先建立稳定家庭，才能共同商议收养。');if(s.children.length>=3)return fail('目前家庭已照料三名孩子，需要专注现有责任。');if(!cost(1200))return fail('收养准备与生活保障需要12银。');days=30;const name=['艾琳','洛伊','希尔'][s.children.length];s.children.push({name,born:s.day+days});title='家中新的一页';text=`经过与修院的商议和一个月的准备，${name}来到你们家中。养育需要耐心，孩子会随着世界一起长大。`;changes.push('家族成员 +1');}
 else if(action==='travel'){const i=Number(arg);if(!Number.isInteger(i)||!regions[i])return fail('目的地无效。');if(i===s.region)return fail('你已经在这里。');if(!isAdult)return fail('年幼的你需要监护人陪同；先在当地成长。');if(weight(s)>maxLoad(s))return fail('行囊超重，请先处理多余物品。');const fee=180+Math.abs(i-s.region)*40;if(!cost(fee))return fail('旅费需要'+money(fee)+'，另需途中食宿。');days=5+Math.abs(i-s.region)*2+(season(s.day)==='冬'?3:0);title='路途与抵达';text=`你搭乘商队，经由驿路抵达${regions[i].town}。新的口音和街道迎面而来，远方的人暂时不知道你的旧事。`;s.region=i;if(!s.known.includes(i))s.known.push(i);s.stamina=clamp(s.stamina-25);changes.push('抵达 '+regions[i].name);}
 else if(action==='buy'){const products:Record<string,[number,number,string]>={'黑面包':[6,.25,'消耗'],'止血草':[20,.1,'消耗'],'铁剑':[900,2.4,'武器'],'皮甲':[700,4,'护甲'],'符文练习板':[150,.8,'材料']};const p=products[arg];if(!p)return fail('商店没有这件物品。');if(weight(s)+p[1]>maxLoad(s))return fail('超过负重上限。');const price=Math.round(p[0]*regions[s.region].price);if(!cost(price))return fail('钱不够，价格为'+money(price)+'。');addItem(s,arg,1,p[1],p[2]);days=0;title='市集交易';text=`你购买了${arg}，交易已记入账册。`;changes.push(arg+' +1');}
 else if(action==='use'){const i=s.items.find(i=>i.name===arg&&i.count>0);if(!i)return fail('背包没有此物。');if(arg==='黑面包'){s.hunger=clamp(s.hunger-22);s.stamina=clamp(s.stamina+6);text='黑面包缓解了饥饿。';}else if(arg==='止血草'){s.hp=clamp(s.hp+8);s.injury=clamp(s.injury-5);text='你清理了浅表伤口，并敷上药草。重伤仍然需要治疗。';}else return fail('此物不能直接消耗使用。');addItem(s,arg,-1);days=0;title='照顾自己';changes.push(arg+' −1');}
 else if(action==='sell'){const i=s.items.find(i=>i.name===arg&&i.count>0);if(!i)return fail('背包没有此物。');const price=arg==='铁剑'?350:arg==='皮甲'?260:arg==='黑面包'?3:arg==='古代碎片'?90:10;addItem(s,arg,-1);s.cash+=price;days=0;title='售出物品';text=`你将一件${arg}售给了本地商贩。`;changes.push('收入 +'+money(price));}
 else if(action==='heal'){if(!cost(120))return fail('医者诊治需1银20铜，另计休养食宿。');days=7;title='疗养的一周';text='医者检查伤口，换药并要求你休息。身体在照料下逐渐恢复。';s.hp=clamp(s.hp+35);s.injury=clamp(s.injury-30);s.stamina=clamp(s.stamina+45);changes.push('生命 +35','伤势 −30');}
 else if(action==='repair'){const fee=s.items.filter(i=>i.slot==='武器'||i.slot==='护甲').length*35;if(!cost(fee))return fail('装备维护费用不足。');s.items.forEach(i=>{if(i.slot==='武器'||i.slot==='护甲')i.durability=100});title='炉火旁的修补';text='你维护了武器与衣甲，磨去锈迹，重新缝好松动的接合处。';changes.push('装备耐久恢复');}
 else if(action==='quest'){if(s.quests.some(q=>q.status==='进行中'))return fail('先完成或放弃当前委托。');const skill=jobs[s.job].skill;const q={id:s.turn,title:jobs[s.job].name+'的试炼委托',skill,need:Math.min(75,s.skills[skill]+5),reward:250+s.rank*100,due:s.day+45,status:'进行中'};s.quests.push(q);days=0;title='一份明确的约定';text=`雇主请你在45日内将${skill}熟练度提高到${q.need}，再完成三日工作。报酬${money(q.reward)}。`;changes.push('新委托');}
 else if(action==='deliver'){const q=s.quests.find(q=>q.status==='进行中');if(!q)return fail('没有可交付的委托。');if(s.skills[q.skill]<q.need)return fail(q.skill+'熟练度需要'+q.need+'。');if(s.day+3>q.due)return fail('完成工作需要3日，已无法按期交付。');days=3;q.status='已完成';s.cash+=q.reward;s.fame[s.region]+=4;title='兑现承诺';text=`你按约完成「${q.title}」。对方付清报酬，记住了一个可靠的名字。`;changes.push('报酬 +'+money(q.reward),'地方声望 +4');}
 else if(action==='abandon'){const q=s.quests.find(q=>q.status==='进行中');if(!q)return fail('没有进行中的委托。');q.status='已放弃';s.fame[s.region]-=1;days=0;title='结束一份委托';text='你提前向雇主说明无法继续，让对方另寻人选。';changes.push('地方声望 −1');}
 else if(action==='estate'){if(!isAdult)return fail('成年后才能独立签订产业契约。');if(s.estate)return fail('你已拥有产业，可继续维护和扩建。');if(s.rank<1||s.skills[jobs[s.job].skill]<20)return fail('开办产业需要至少见习身份、职业技能20。');if(!cost(5000))return fail('开办小型工坊需要50银。');days=30;s.estate={name:jobs[s.job].name+'小工坊',level:1,condition:100,workers:0,revenue:0};title='挂起自己的招牌';text='租约、工具和修缮占去了一个月。今天，你终于在门口挂上自己的招牌。';changes.push('解锁产业经营');}
 else if(action==='maintain'){if(!s.estate)return fail('尚无产业。');if(!cost(120))return fail('维护需要1银20铜。');s.estate.condition=100;days=3;title='维持运转';text='你修理工具，整理库存，让工坊恢复良好状态。';changes.push('产业状态恢复');}
 else if(action==='expand'){if(!s.estate)return fail('尚无产业。');if(s.estate.level>=5)return fail('工坊已达到当前最大规模。');if(!cost(s.estate.level*2500))return fail('扩建需要'+money(s.estate.level*2500)+'。');days=30;s.estate.level++;s.estate.workers++;title='工坊扩建';text='你安排一个月工期，添置设备，并雇用一位帮手。每月工资会自动计入经营成本。';changes.push('产业规模 +1','雇员 +1');}
 else if(action==='borrow'){if(!isAdult)return fail('未成年不能独立借款。');if(s.debt)return fail('请先清偿已有债务。');s.debt=1100;s.debtDue=s.day+90;s.cash+=1000;title='一纸借据';text='你借入10银，约定90日内偿还11银。逾期后每30日按未偿金额追加3%利息。';changes.push('现金 +10银','到期债务 11银');}
 else if(action==='repay'){if(!s.debt)return fail('你没有债务。');if(!cost(s.debt))return fail('现金不足以结清债务。');s.debt=0;days=0;title='归还借据';text='债权人在借据上注明结清，并将副本交还给你。';changes.push('债务清零');}
 else if(action==='cast'){if(!s.maxMana||s.skills.元素<15)return fail('施法需魔法潜质、元素熟练度15。');if(s.mana<8)return fail('魔力不足8，请先休息恢复。');s.mana-=8;s.spirit=clamp(s.spirit-5);gain(s,'元素',1);title='掌心的微光';text='你按照学过的符文引导以太，一簇微光照亮了掌心。它短暂而真实，不能替代漫长的学习。';changes.push('魔力 −8','元素熟练度 +1');}
 else if(action==='year'){if(s.quests.some(q=>q.status==='进行中')||s.debt)return fail('请先处理委托和债务，才能安心安排一年生活。');if(s.injury>10||s.hp<70)return fail('先治疗伤势，再安排长期生活。');days=360;const j=jobs[s.job];const gross=Math.round((isAdult?j.base+s.rank*20:26)*240*difficulty(s).income);s.cash+=gross;gain(s,j.skill,12);s.stamina=80;s.spirit=80;title='岁月向前翻了一页';text=`你把一年分给${isAdult?'工作':'学习'}、休息和家庭，完成约240日劳作。季节更替中，${j.skill}变得更熟练，街坊也有了新的面孔。`;changes.push('年度毛收入 +'+money(gross),j.skill+'熟练度 +12');}
 else if(action==='retire'){days=0;s.retired=true;title='把往后的日子留给自己';text=`你选择在${regions[s.region].town}安定下来。${jobTitle(s)}、${money(s.cash)}积蓄、${s.children.length}名子女，这些只是人生的一部分。你留下的承诺和关系，仍有人记得。`;changes.push('人生结算','目标：'+s.draft.goal);}
 else if(action==='event'){const e=events.find(e=>e.id===s.event);const c=e?.choices[Number(arg)];if(!e||!c)return fail('请选择有效事件选项。');if(c.cost&&!cost(c.cost))return fail('这项选择需要'+money(c.cost)+'。');days=c.days;title=e.title+' · '+c.label;let success=true;if(c.difficulty!==undefined){const gearBonus=c.skill==='剑术'&&s.items.some(i=>i.name==='铁剑'&&i.durability>0)?8:0;const threshold=clamp(50+(s.attributes.感知-10)*3+(s.skills[c.skill||'生存']||0)*.4-c.difficulty+gearBonus+difficulty(s).risk,5,95);success=rand(s)*100<threshold;}text=success?`你选择了「${c.label}」。事情有了进展，${c.follow||'这段经历成为你与这片土地之间的一条细小联系。'}`:`你尝试了「${c.label}」，但经验或条件还不够。这次没有获得预期的报酬，你记下不足，仍然可以寻找别的道路。`;if(c.skill){gain(s,c.skill,success?4:2,!!c.breakthrough);changes.push(c.skill+'熟练度 +'+(success?4:2))}if(success){if(c.reward){s.cash+=c.reward;changes.push('收入 +'+money(c.reward))}if(c.item){addItem(s,c.item,1);changes.push(c.item+' +1')}if(c.fame){s.fame[s.region]+=c.fame;changes.push('地方声望 +'+c.fame)}if(c.trust){const n=s.npcs.find(n=>n.id===(e.id==='mentor'?'mentor':'friend')&&n.alive);if(n){n.trust=clamp(n.trust+c.trust);changes.push(n.name+'信任 +'+c.trust)}}}else if(c.hurt){s.hp=clamp(s.hp-Math.round(c.hurt*difficulty(s).hurt*(s.items.some(i=>i.name==='皮甲'&&i.durability>0)?.8:1)));s.injury=clamp(s.injury+c.hurt/2);changes.push('生命 −'+Math.round(c.hurt*difficulty(s).hurt*(s.items.some(i=>i.name==='皮甲'&&i.durability>0)?.8:1)))}s.seen[e.id]=s.day;s.event=null;}
 else return fail('暂不支持这个行动。可输入：工作、休息、探索、训练 剑术、旅行 洛恩王国，或点击面板操作。');
 advance(s,days,changes);s.turn++;if(days>0&&['work','explore','event'].includes(action))s.items.forEach(i=>{if(i.slot==='武器'||i.slot==='护甲')i.durability=clamp(i.durability-1)});entry(s,title,text,changes);if(s.dead)entry(s,'终章 · 留在世间的名字',`${s.draft.name}的一生在${regions[s.region].town}落下帷幕。你留下${money(s.cash)}积蓄、${s.log.length}段经历，以及与身边人的关系。`,['最终身份：'+jobTitle(s),'人生目标：'+s.draft.goal]);
 if(!s.dead&&!s.retired&&action!=='event'&&days>0&&(s.turn%4===0||action==='explore'||action==='year')){const pool=events.filter(e=>(!e.condition||e.condition(s))&&(s.seen[e.id]===undefined||s.day-s.seen[e.id]>90));const breakthroughs=pool.filter(e=>e.kind==='突破');const selected=breakthroughs.length?breakthroughs:pool;if(selected.length)s.event=selected[Math.floor(rand(s)*selected.length)].id;}
 return {state:s};
}
export function inherit(s:Game):Game|null{const child=s.children.find(c=>(s.day-c.born)/360>=adultAge(s.draft.race));if(!child||(!s.dead&&!s.retired))return null;const n=createGame({...s.draft,name:child.name,age:'成年 · 适龄'},s.mode);n.day=s.day;n.ageStart=Math.floor((s.day-child.born)/360)-Math.floor(s.day/360);n.cash=s.cash;n.debt=s.debt;n.debtDue=s.debtDue;n.estate=s.estate?structuredClone(s.estate):null;n.region=s.region;n.known=[...s.known];n.fame=s.fame.map(f=>Math.round(f*.35));n.log=[...s.log];n.generation=s.generation+1;n.seed=s.seed;entry(n,'新的执笔人',`${child.name}接过家中的账册。资产、债务与世界历史仍在，技艺需要自己重新学习。`,['第'+n.generation+'代']);return n;}
export function parseCommand(text:string):[string,string]{const t=text.trim().replace(/[【】]/g,'');const panels=['属性','背包','技能','关系','任务','地图','势力','领地','日志','装备','魔法','家族','存档','规则','职业','市场','托管'];if(panels.includes(t))return ['panel',t];const direct:Record<string,string>={工作:'work',休息:'rest',探索:'explore',治疗:'heal',晋升:'promote',一年:'year',快进一年:'year',领取委托:'quest',交付委托:'deliver',借款:'borrow',还款:'repay',施法:'cast',返回:'return'};if(direct[t])return [direct[t],''];if(t.startsWith('训练')&&skillNames.includes(t.slice(2).trim()))return ['train',t.slice(2).trim()];if(t.startsWith('旅行')&&regions.some(r=>r.name===t.slice(2).trim()))return ['travel',String(regions.findIndex(r=>r.name===t.slice(2).trim()))];return ['unknown',''];}
export function validSave(v:unknown):v is Game{if(!v||typeof v!=='object')return false;const s=v as Game;const h=s.hosting;const validHosting=h===undefined||!!h&&['work','explore'].includes(h.action)&&['adventure','balanced','cautious'].includes(h.temperament)&&[h.staminaBelow,h.hpBelow,h.staminaRecoverTo??null,h.hpRecoverTo??null].every(x=>x===null||Number.isInteger(x)&&x>=0&&x<=100)&&(h.resting===undefined||typeof h.resting==='boolean')&&typeof h.active==='boolean'&&Number.isInteger(h.completed)&&h.completed>=0&&typeof h.reason==='string';return validHosting&&(s.aiGoal===undefined||validLifeGoal(s.aiGoal))&&s.version===1&&typeof s.id==='string'&&!!s.draft&&typeof s.draft.name==='string'&&steps.every(x=>typeof s.draft[x.key]==='string')&&Number.isInteger(s.day)&&s.day>=0&&s.day<3600000&&Number.isInteger(s.region)&&s.region>=0&&s.region<6&&Number.isInteger(s.job)&&!!jobs[s.job]&&[s.cash,s.debt,s.hp,s.stamina,s.spirit,s.mana,s.maxMana,s.hunger,s.injury,s.seed,s.turn,s.ageStart,s.rank,s.generation,s.debtDue,s.crime].every(Number.isFinite)&&s.cash>=0&&s.debt>=0&&s.hp>=0&&s.hp<=100&&s.stamina>=0&&s.stamina<=100&&s.spirit>=0&&s.spirit<=100&&s.mana>=0&&s.mana<=s.maxMana&&s.rank>=0&&s.rank<=3&&!!s.attributes&&attrNames.every(k=>Number.isFinite(s.attributes[k]))&&!!s.skills&&skillNames.every(k=>Number.isFinite(s.skills[k])&&s.skills[k]>=0&&s.skills[k]<=120)&&Array.isArray(s.log)&&s.log.every(e=>typeof e.title==='string'&&typeof e.text==='string'&&Array.isArray(e.changes)&&e.changes.every(c=>typeof c==='string')&&Number.isFinite(e.day))&&Array.isArray(s.items)&&s.items.every(i=>typeof i.name==='string'&&typeof i.slot==='string'&&Number.isInteger(i.count)&&i.count>0&&Number.isFinite(i.weight)&&i.weight>=0&&Number.isFinite(i.durability))&&Array.isArray(s.npcs)&&s.npcs.every(n=>typeof n.id==='string'&&typeof n.name==='string'&&[n.age,n.trust,n.affinity,n.last].every(Number.isFinite))&&Array.isArray(s.quests)&&s.quests.every(q=>typeof q.title==='string'&&typeof q.status==='string'&&skillNames.includes(q.skill)&&[q.id,q.need,q.reward,q.due].every(Number.isFinite))&&Array.isArray(s.children)&&s.children.every(c=>typeof c.name==='string'&&Number.isFinite(c.born))&&Array.isArray(s.fame)&&s.fame.length===6&&s.fame.every(Number.isFinite)&&Array.isArray(s.known)&&s.known.every(i=>Number.isInteger(i)&&i>=0&&i<6)&&!!s.seen&&typeof s.seen==='object'&&(s.event===null||events.some(e=>e.id===s.event))&&(s.estate===null||typeof s.estate.name==='string'&&[s.estate.level,s.estate.condition,s.estate.workers,s.estate.revenue].every(Number.isFinite))&&typeof s.mode==='string'&&typeof s.dead==='boolean'&&typeof s.retired==='boolean';}
